# GitHub Dependabot configuration for automated dependency updates
version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@dependabot[bot]"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # NPM dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@dependabot[bot]"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "@dependabot[bot]"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"