services:
  - type: web
    name: gestao-pedidos-distribuido
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        value: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - key: DATABASE_USERNAME
        value: sa
      - key: DATABASE_PASSWORD
        value: 
      - key: DATABASE_DRIVER
        value: org.h2.Driver
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.H2Dialect
      - key: RABBITMQ_HOST
        value: localhost
      - key: RABBITMQ_PORT
        value: 5672
      - key: RABBITMQ_USERNAME
        value: guest
      - key: RABBITMQ_PASSWORD
        value: guest
      - key: JWT_SECRET_KEY
        value: renderSecretKeyForProduction2024
      - key: JAVA_OPTS
        value: -Xmx400m -XX:+UseContainerSupport
