services:
  # PostgreSQL Database
  - type: pserv
    name: order-postgres-db
    plan: starter
    region: oregon
    databaseName: order_system_db
    databaseUser: order_system_user
    ipAllowList: []

  # Redis Instance
  - type: redis
    name: order-redis-cache
    plan: starter
    region: oregon
    ipAllowList: []

  # Unified Application (Frontend + Backend)
  - type: web
    name: gestao-de-pedidos
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    buildCommand: ""  # Docker handles the build
    startCommand: ""  # Docker handles the start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: order-postgres-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: order-postgres-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: order-postgres-db
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: order-redis-cache
          property: connectionString
      - key: MESSAGING_TYPE
        value: redis
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Dspring.jpa.hibernate.ddl-auto=update"