services:
  - type: web
    name: gestao-de-pedidos
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

