server:
  port: ${PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/orderdb}
    username: ${DATABASE_USERNAME:order_user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 10
      
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: false
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 1000ms
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

logging:
  level:
    com.ordersystem: INFO
    root: WARN
    org.springframework.boot.web.embedded.tomcat: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  server:
    port: ${PORT:8080}
