server:
  port: 8084
  address: 0.0.0.0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/querydb}
    username: ${DATABASE_USERNAME:query_user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 10
      
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: false

logging:
  level:
    com.ordersystem: INFO
    root: WARN
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
